import "dotenv/config";
import { app, BrowserWindow, ipcMain, screen, dialog } from "electron";
import path from "node:path";
import fs from "node:fs";
import {
  MCPClientManager,
  logger,
  initializeFileLogging,
  ConfigManager,
} from "./client";
import type {
  MCPServerConfig,
  ServerInfo,
  ToolExecutionResult,
} from "./client/types";
import { StudyAgentService } from "./agent/StudyAgentService";
import { dbManager } from "./client/DatabaseManager";
import type { ChatMessage, UploadedDocument } from "./client/DatabaseManager";
import { startChromaServer, stopChromaServer } from "./rag/chroma-server";

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require("electron-squirrel-startup")) {
  app.quit();
}

// Initialize MCP Client Manager
const mcpManager = new MCPClientManager();
const studyAgentService = new StudyAgentService();
const configManager = new ConfigManager();

const createWindow = (): void => {
  // Get primary display work area size
  const { width, height } = screen.getPrimaryDisplay().workAreaSize;

  // Create the browser window with dynamic screen dimensions
  const mainWindow = new BrowserWindow({
    width,
    height,
    autoHideMenuBar: true,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: false,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  mainWindow.webContents.openDevTools();

  logger.info("Main window created");
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on("ready", async () => {
  // Initialize file logging now that app is ready
  await initializeFileLogging();

  // Start ChromaDB server for persistent vector storage
  try {
    await startChromaServer();
    logger.info("ChromaDB server started successfully");
  } catch (error) {
    logger.error("Failed to start ChromaDB server", error);
  }

  // Initialize database BEFORE registering IPC handlers
  try {
    dbManager.initialize();
    logger.info("Database initialized", dbManager.getStats());
  } catch (error) {
    logger.error("Failed to initialize database", error);
  }

  // Register database IPC handlers AFTER database is initialized
  registerDatabaseHandlers();

  createWindow();

  // Warm up the Study Agent so the UI immediately shows status
  studyAgentService.initialize().catch((error) => {
    logger.error("Study agent failed to initialize on startup", error);
  });
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    app.quit();
  }
});

app.on("activate", () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// Log GPU child process exits so we can monitor stability without noisy Chromium errors
app.on("child-process-gone", (_event, details) => {
  if (details.type === "GPU") {
    logger.warn("GPU process exited, continuing with software rendering", {
      reason: details.reason,
      exitCode: details.exitCode,
    });
  }
});

// Cleanup on quit
app.on("before-quit", async () => {
  logger.info("Application quitting, cleaning up resources...");
  await mcpManager.disconnectAll();
  await studyAgentService.dispose();
  await stopChromaServer();
  dbManager.close();
  logger.info("All resources cleaned up");
});

// ========================================
// IPC Handlers for MCP Client Operations
// ========================================

/**
 * Add and connect to a new MCP server
 */
ipcMain.handle(
  "mcp:addServer",
  async (
    _,
    config: MCPServerConfig
  ): Promise<{ success: boolean; error?: string }> => {
    try {
      logger.info("Adding MCP server:", config.name);
      await mcpManager.addServer(config);
      return { success: true };
    } catch (error) {
      logger.error("Failed to add MCP server:", error);
      return {
        success: false,
        error: error instanceof Error ? error.message : String(error),
      };
    }
  }
);

/**
 * Remove a server connection
 */
ipcMain.handle(
  "mcp:removeServer",
  async (
    _,
    serverId: string
  ): Promise<{ success: boolean; error?: string }> => {
    try {
      logger.info("Removing MCP server:", serverId);
      await mcpManager.removeServer(serverId);
      return { success: true };
    } catch (error) {
      logger.error("Failed to remove MCP server:", error);
      return {
        success: false,
        error: error instanceof Error ? error.message : String(error),
      };
    }
  }
);

/**
 * Get information about a specific server
 */
ipcMain.handle(
  "mcp:getServerInfo",
  (_, serverId: string): ServerInfo | undefined => {
    return mcpManager.getServerInfo(serverId);
  }
);

/**
 * Get information about all servers
 */
ipcMain.handle("mcp:getAllServers", (): ServerInfo[] => {
  return mcpManager.getAllServers();
});

/**
 * Get all available tools from all connected servers
 */
ipcMain.handle("mcp:getAllTools", () => {
  return mcpManager.getAllTools();
});

/**
 * Execute a tool on a specific server
 */
ipcMain.handle(
  "mcp:executeTool",
  async (
    _,
    serverId: string,
    toolName: string,
    args?: Record<string, unknown>
  ): Promise<ToolExecutionResult> => {
    logger.info(`Executing tool ${toolName} on server ${serverId}`, args);
    return mcpManager.executeTool(serverId, toolName, args);
  }
);

/**
 * Find which server has a specific tool
 */
ipcMain.handle(
  "mcp:findToolServer",
  (_, toolName: string): string | undefined => {
    return mcpManager.findToolServer(toolName);
  }
);

/**
 * Get the count of connected servers
 */
ipcMain.handle("mcp:getConnectedCount", (): number => {
  return mcpManager.getConnectedCount();
});

ipcMain.handle(
  "agent:sendMessage",
  async (
    _,
    payload: { threadId: string; message: string }
  ): Promise<Awaited<ReturnType<typeof studyAgentService.sendMessage>>> => {
    logger.info("Agent invocation requested", { threadId: payload.threadId });
    return studyAgentService.sendMessage(payload.message, payload.threadId);
  }
);

ipcMain.handle("agent:getStatus", async () => {
  await studyAgentService.initialize().catch((error) => {
    logger.warn(
      "Agent status requested before initialization completed",
      error
    );
  });
  return studyAgentService.getStatus();
});

ipcMain.handle(
  "agent:reloadDocuments",
  async (_event, documentPaths: string[]) => {
    logger.info("Agent document reload requested", { documentPaths });
    await studyAgentService.reloadDocuments(documentPaths);
    return studyAgentService.getStatus();
  }
);

ipcMain.handle("agent:openFileDialog", async () => {
  const result = await dialog.showOpenDialog({
    properties: ["openFile", "multiSelections"],
    filters: [
      { name: "Documents", extensions: ["pdf", "txt", "md", "mdx"] },
      { name: "Code Files", extensions: ["ts", "tsx", "js", "jsx", "json"] },
      { name: "All Files", extensions: ["*"] },
    ],
  });

  if (result.canceled || result.filePaths.length === 0) {
    return { success: false, filePaths: [] };
  }

  return { success: true, filePaths: result.filePaths };
});

ipcMain.handle(
  "agent:addDocuments",
  async (_event, documentPaths: string[]) => {
    logger.info("Agent add documents requested", { documentPaths });

    try {
      // Mark documents as processing in database
      const trackedDocs: Array<{ docId: string; filePath: string }> = [];
      const ingestPaths: string[] = [];
      const skippedExisting: string[] = [];
      for (const filePath of documentPaths) {
        const absolutePath = path.isAbsolute(filePath)
          ? path.resolve(filePath)
          : path.resolve(process.cwd(), filePath);
        // Check if already uploaded
        const existing = dbManager.getDocumentByPath(absolutePath);
        if (existing) {
          logger.info(`Document already uploaded: ${absolutePath}`);
          skippedExisting.push(absolutePath);
          continue;
        }

        const docId = `doc-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
        const fileName = path.basename(absolutePath);
        const fileType = path.extname(absolutePath);
        const fileSize = fs.existsSync(absolutePath)
          ? fs.statSync(absolutePath).size
          : 0;

        const doc: UploadedDocument = {
          id: docId,
          filePath: absolutePath,
          fileName,
          fileType,
          fileSize,
          chunkCount: 0,
          uploadedAt: Date.now(),
          status: "processing",
        };

        dbManager.saveDocument(doc);
        trackedDocs.push({ docId, filePath: absolutePath });
        ingestPaths.push(absolutePath);
      }

      if (ingestPaths.length === 0) {
        logger.info(
          "Skipping ingestion request because all documents already exist or were invalid"
        );
        return {
          success: false,
          addedCount: 0,
          errors:
            skippedExisting.length > 0
              ? [
                  "All selected documents were already uploaded. Remove duplicates or provide new files.",
                ]
              : ["No documents provided for ingestion."],
          documentStats: {},
        };
      }

      // Process documents through agent
      const result = await studyAgentService.addDocuments(ingestPaths);
      const duplicateWarnings = skippedExisting.map(
        (filePath) =>
          `Skipped ${path.basename(filePath)} because it was already uploaded. Delete it first or upload a revised version.`
      );

      // Update document status in database
      if (result.success) {
        for (const doc of trackedDocs) {
          const stats =
            result.documentStats[path.resolve(doc.filePath)] ?? null;
          if (stats) {
            dbManager.updateDocumentStatus(doc.docId, "ready");
            dbManager.updateDocumentChunkCount(doc.docId, stats.chunkCount);
          } else {
            dbManager.updateDocumentStatus(
              doc.docId,
              "error",
              "File did not yield usable text."
            );
          }
        }

        // Update vector store state
        const currentState = dbManager.getVectorStoreState();
        const previousDocuments = currentState?.totalDocuments ?? 0;
        const previousChunks = currentState?.totalChunks ?? 0;
        const addedChunks = Object.values(result.documentStats).reduce(
          (sum, stats) => sum + stats.chunkCount,
          0
        );

        dbManager.updateVectorStoreState(
          previousDocuments + result.addedCount,
          previousChunks + addedChunks,
          {
            lastIngestedAt: Date.now(),
            lastDocuments: Object.values(result.documentStats).map((stats) => ({
              absolutePath: stats.absolutePath,
              chunkCount: stats.chunkCount,
              origin: stats.origin,
            })),
          }
        );
      } else {
        for (const doc of trackedDocs) {
          dbManager.updateDocumentStatus(
            doc.docId,
            "error",
            result.errors.join(", ")
          );
        }
      }

      if (duplicateWarnings.length === 0) {
        return result;
      }

      return {
        ...result,
        errors: [...result.errors, ...duplicateWarnings],
      };
    } catch (error) {
      logger.error("Failed to add documents", error);
      return {
        success: false,
        addedCount: 0,
        errors: [error instanceof Error ? error.message : String(error)],
        documentStats: {},
      };
    }
  }
);

ipcMain.handle("config:getSummary", () => {
  return configManager.getSummary();
});

ipcMain.handle(
  "config:update",
  async (_event, values: Record<string, string | undefined>) => {
    await configManager.update(values);
    return configManager.getSummary();
  }
);

// ========================================
// Database IPC Handlers
// ========================================

/**
 * Register database IPC handlers after database is initialized
 * This ensures the database is ready before any IPC calls are made
 */
function registerDatabaseHandlers() {
  ipcMain.handle("db:saveMessage", (_event, message: ChatMessage) => {
    try {
      dbManager.saveMessage(message);
      return { success: true };
    } catch (error) {
      logger.error("Failed to save message", error);
      return {
        success: false,
        error: error instanceof Error ? error.message : String(error),
      };
    }
  });

  ipcMain.handle(
    "db:getMessages",
    (_event, threadId: string, limit?: number) => {
      try {
        return dbManager.getMessages(threadId, limit);
      } catch (error) {
        logger.error("Failed to get messages", error);
        return [];
      }
    }
  );

  ipcMain.handle("db:clearMessages", (_event, threadId: string) => {
    try {
      dbManager.clearMessages(threadId);
      return { success: true };
    } catch (error) {
      logger.error("Failed to clear messages", error);
      return {
        success: false,
        error: error instanceof Error ? error.message : String(error),
      };
    }
  });

  ipcMain.handle("db:createThread", (_event, id: string, title: string) => {
    try {
      dbManager.createThread(id, title);
      return { success: true };
    } catch (error) {
      logger.error("Failed to create thread", error);
      return {
        success: false,
        error: error instanceof Error ? error.message : String(error),
      };
    }
  });

  ipcMain.handle("db:getAllThreads", () => {
    try {
      return dbManager.getAllThreads();
    } catch (error) {
      logger.error("Failed to get threads", error);
      return [];
    }
  });

  ipcMain.handle("db:getAllDocuments", () => {
    try {
      return dbManager.getAllDocuments();
    } catch (error) {
      logger.error("Failed to get documents", error);
      return [];
    }
  });

  ipcMain.handle("db:deleteDocument", (_event, id: string) => {
    try {
      dbManager.deleteDocument(id);
      return { success: true };
    } catch (error) {
      logger.error("Failed to delete document", error);
      return {
        success: false,
        error: error instanceof Error ? error.message : String(error),
      };
    }
  });

  ipcMain.handle("db:getStats", () => {
    try {
      return dbManager.getStats();
    } catch (error) {
      logger.error("Failed to get database stats", error);
      return { threads: 0, messages: 0, documents: 0, dbSizeMB: 0 };
    }
  });

  logger.info("Database IPC handlers registered");
}

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
