import "dotenv/config";
import { app, BrowserWindow, ipcMain, screen, dialog } from "electron";
import path from "node:path";
import fs from "node:fs";
import {
  MCPClientManager,
  logger,
  initializeFileLogging,
  ConfigManager,
  mcpToolService,
} from "./client";
import { loadMcpConfig } from "./tools/mcp-loader";
import {
  HumanMessage,
  AIMessage,
  SystemMessage,
  type BaseMessage,
} from "@langchain/core/messages";
import type {
  MCPServerConfig,
  ServerInfo,
  ToolExecutionResult,
} from "./client/types";
import { StudyAgentService } from "./agent/StudyAgentService";
import { dbManager } from "./client/DatabaseManager";
import type { ChatMessage, UploadedDocument } from "./client/DatabaseManager";
import { startRAGService, stopRAGService } from "./rag/rag-service-manager";

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require("electron-squirrel-startup")) {
  app.quit();
}

// Initialize MCP Client Manager
const mcpManager = new MCPClientManager();
mcpToolService.setMCPManager(mcpManager);

logger.info("=".repeat(60));
logger.info("🚀 AI Study Agent - Starting Up");
logger.info("=".repeat(60));

// Load MCP servers from config
const mcpConfig = loadMcpConfig();
logger.info(`📋 Loading MCP configuration from mcp.json`);
logger.info(
  `Found ${Object.keys(mcpConfig.mcpServers).length} MCP servers configured`
);

for (const [id, config] of Object.entries(mcpConfig.mcpServers)) {
  if (config.command) {
    logger.info(`🔌 Adding MCP server: ${id}`);
    logger.info(
      `   Command: ${config.command} ${(config.args || []).join(" ")}`
    );
    mcpManager
      .addServer({
        id,
        name: id,
        command: config.command,
        args: config.args || [],
        env: config.env,
      })
      .then(() => logger.info(`✅ MCP server ${id} connected successfully`))
      .catch((err) => {
        logger.error(`❌ Failed to add MCP server ${id}:`, err);
        logger.error(`   This may affect tool availability`);
      });
  }
}

logger.info("🤖 Initializing Study Agent Service with MCP Manager");
const studyAgentService = new StudyAgentService({}, mcpManager);
const configManager = new ConfigManager();

logger.info("📊 Study Agent ready for initialization");
logger.info("=".repeat(60));

function convertChatHistoryToMessages(
  history: ChatMessage[],
  excludeMessageId?: string
): BaseMessage[] {
  return history
    .filter((msg) => (excludeMessageId ? msg.id !== excludeMessageId : true))
    .map((msg) => {
      switch (msg.role) {
        case "assistant":
          return new AIMessage(msg.content);
        case "system":
          return new SystemMessage(msg.content);
        default:
          return new HumanMessage(msg.content);
      }
    });
}

const createWindow = (): void => {
  // Get primary display work area size
  const { width, height } = screen.getPrimaryDisplay().workAreaSize;

  // Create the browser window with dynamic screen dimensions
  const mainWindow = new BrowserWindow({
    width,
    height,
    autoHideMenuBar: true,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: false,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  mainWindow.webContents.openDevTools();

  logger.info("🪟 Main window created and DevTools opened");
  logger.info(`   Size: ${width}x${height}`);
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on("ready", async () => {
  logger.info("\n" + "=".repeat(60));
  logger.info("⚡ Electron App Ready - Initializing Services");
  logger.info("=".repeat(60));

  // Initialize file logging now that app is ready
  await initializeFileLogging();
  logger.info("📝 File logging initialized");

  // Initialize database BEFORE registering IPC handlers
  try {
    dbManager.initialize();
    const stats = dbManager.getStats();
    logger.info("💾 Database initialized successfully");
    logger.info(`   Conversation threads: ${stats.threads}`);
    logger.info(`   Total messages: ${stats.messages}`);
    logger.info(`   Uploaded documents: ${stats.documents}`);
    logger.info(`   Database size: ${stats.dbSizeMB.toFixed(2)} MB`);
  } catch (error) {
    logger.error("❌ Failed to initialize database:", error);
  }

  // Register database IPC handlers AFTER database is initialized
  registerDatabaseHandlers();
  logger.info("🔌 IPC handlers registered");

  // Start NVIDIA RAG service after database is ready
  try {
    logger.info("🚀 Starting NVIDIA RAG service...");
    await startRAGService();
    logger.info("✅ NVIDIA RAG service started successfully");
    logger.info("   Model: nvidia/llama-3.2-nemoretriever-300m-embed-v2");
    logger.info("   LLM: moonshotai/kimi-k2-instruct (via OpenAI SDK)");
  } catch (error) {
    logger.error("❌ Failed to start NVIDIA RAG service:", error);
    logger.error("   RAG features may not be available");
  }

  createWindow();

  // Warm up the Study Agent so the UI immediately shows status
  logger.info("\n🔥 Warming up Study Agent...");
  studyAgentService
    .initialize()
    .then(() => {
      logger.info("✅ Study Agent initialized and ready");
      logger.info("=".repeat(60));
      logger.info("🎉 All systems operational - Ready for queries!");
      logger.info("=".repeat(60) + "\n");
    })
    .catch((error) => {
      logger.error("❌ Study agent failed to initialize on startup:", error);
      logger.warn("   Agent will initialize on first query instead");
    });
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on("window-all-closed", () => {
  // Always quit on all platforms for consistent behavior
  app.quit();
});

app.on("activate", () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// Log GPU child process exits so we can monitor stability without noisy Chromium errors
app.on("child-process-gone", (_event, details) => {
  if (details.type === "GPU") {
    logger.warn("GPU process exited, continuing with software rendering", {
      reason: details.reason,
      exitCode: details.exitCode,
    });
  }
});

// Cleanup on quit - prevent multiple cleanup calls
let isCleaningUp = false;
app.on("before-quit", async (event) => {
  if (isCleaningUp) return;

  // Prevent default quit to allow async cleanup
  event.preventDefault();
  isCleaningUp = true;

  logger.info("Application quitting, cleaning up resources...");

  try {
    await mcpManager.disconnectAll();
    await studyAgentService.dispose();
    await stopRAGService();
    dbManager.close();
    logger.info("All resources cleaned up");
  } catch (error) {
    logger.error("Error during cleanup", error);
  }

  // Now actually quit
  app.exit(0);
});

// ========================================
// IPC Handlers for MCP Client Operations
// ========================================

/**
 * Add and connect to a new MCP server
 */
ipcMain.handle(
  "mcp:addServer",
  async (
    _,
    config: MCPServerConfig
  ): Promise<{ success: boolean; error?: string }> => {
    try {
      logger.info("Adding MCP server:", config.name);
      await mcpManager.addServer(config);
      return { success: true };
    } catch (error) {
      logger.error("Failed to add MCP server:", error);
      return {
        success: false,
        error: error instanceof Error ? error.message : String(error),
      };
    }
  }
);

/**
 * Remove a server connection
 */
ipcMain.handle(
  "mcp:removeServer",
  async (
    _,
    serverId: string
  ): Promise<{ success: boolean; error?: string }> => {
    try {
      logger.info("Removing MCP server:", serverId);
      await mcpManager.removeServer(serverId);
      return { success: true };
    } catch (error) {
      logger.error("Failed to remove MCP server:", error);
      return {
        success: false,
        error: error instanceof Error ? error.message : String(error),
      };
    }
  }
);

/**
 * Get information about a specific server
 */
ipcMain.handle(
  "mcp:getServerInfo",
  (_, serverId: string): ServerInfo | undefined => {
    return mcpManager.getServerInfo(serverId);
  }
);

/**
 * Get information about all servers
 */
ipcMain.handle("mcp:getAllServers", (): ServerInfo[] => {
  return mcpManager.getAllServers();
});

/**
 * Get all available tools from all connected servers
 */
ipcMain.handle("mcp:getAllTools", () => {
  return mcpManager.getAllTools();
});

/**
 * Execute a tool on a specific server
 */
ipcMain.handle(
  "mcp:executeTool",
  async (
    _,
    serverId: string,
    toolName: string,
    args?: Record<string, unknown>
  ): Promise<ToolExecutionResult> => {
    logger.info(`Executing tool ${toolName} on server ${serverId}`, args);
    return mcpManager.executeTool(serverId, toolName, args);
  }
);

/**
 * Find which server has a specific tool
 */
ipcMain.handle(
  "mcp:findToolServer",
  (_, toolName: string): string | undefined => {
    return mcpManager.findToolServer(toolName);
  }
);

/**
 * Get the count of connected servers
 */
ipcMain.handle("mcp:getConnectedCount", (): number => {
  return mcpManager.getConnectedCount();
});

/**
 * Request tool execution with approval flow
 */
ipcMain.handle(
  "mcp:requestToolExecution",
  async (
    _,
    payload: {
      toolName: string;
      serverId: string;
      serverName: string;
      args?: Record<string, unknown>;
      description?: string;
    }
  ): Promise<{ requestId: string }> => {
    try {
      logger.info("Tool execution requested", payload);
      const request = await mcpToolService.requestToolExecution(
        payload.toolName,
        payload.serverId,
        payload.serverName,
        payload.args,
        payload.description
      );
      return { requestId: request.id };
    } catch (error) {
      logger.error("Failed to create tool execution request:", error);
      throw error;
    }
  }
);

/**
 * Approve a tool execution request
 */
ipcMain.handle(
  "mcp:approveToolExecution",
  async (_, requestId: string): Promise<void> => {
    try {
      logger.info("Tool execution approved", { requestId });
      await mcpToolService.approveExecution(requestId);
    } catch (error) {
      logger.error("Failed to approve tool execution:", error);
      throw error;
    }
  }
);

/**
 * Deny a tool execution request
 */
ipcMain.handle(
  "mcp:denyToolExecution",
  async (_, requestId: string): Promise<void> => {
    try {
      logger.info("Tool execution denied", { requestId });
      mcpToolService.denyExecution(requestId);
    } catch (error) {
      logger.error("Failed to deny tool execution:", error);
      throw error;
    }
  }
);

/**
 * Get pending tool execution requests
 */
ipcMain.handle("mcp:getPendingToolRequests", () => {
  const pending = mcpToolService.getPendingRequests();
  return pending.map((req) => mcpToolService.toPendingToolCall(req));
});

ipcMain.handle(
  "agent:sendMessage",
  async (
    _,
    payload: { threadId: string; message: string; messageId?: string }
  ) => {
    logger.info("\n" + "─".repeat(60));
    logger.info("💬 New Agent Query Received");
    logger.info("─".repeat(60));
    logger.info(`Thread ID: ${payload.threadId}`);
    logger.info(
      `Message: ${payload.message.substring(0, 100)}${payload.message.length > 100 ? "..." : ""}`
    );

    let conversationHistory: BaseMessage[] = [];
    try {
      const historyRecords = dbManager.getMessages(payload.threadId);
      conversationHistory = convertChatHistoryToMessages(
        historyRecords,
        payload.messageId
      );
      logger.info(
        `📚 Loaded ${conversationHistory.length} messages from history`
      );
    } catch (error) {
      logger.warn("⚠️  Failed to load conversation history", {
        threadId: payload.threadId,
        error,
      });
    }

    logger.info("🤖 Invoking Study Agent with NVIDIA Kimi-K2-Instruct...");
    const startTime = Date.now();

    const result = await studyAgentService.invoke(
      payload.message,
      conversationHistory,
      { threadId: payload.threadId }
    );

    const duration = Date.now() - startTime;
    logger.info("✅ Agent response generated");
    logger.info(`⏱️  Processing time: ${duration}ms`);
    const responseText = result.finalMessage || "";
    logger.info(`📝 Response length: ${responseText.length} characters`);
    if (responseText.length > 0) {
      logger.info(
        `Response preview: ${responseText.substring(0, 150)}${responseText.length > 150 ? "..." : ""}`
      );
    }
    logger.info("─".repeat(60) + "\n");

    return result;
  }
);

ipcMain.handle("agent:getStatus", async () => {
  await studyAgentService.initialize().catch((error) => {
    logger.warn(
      "Agent status requested before initialization completed",
      error
    );
  });
  return studyAgentService.getStatus();
});

ipcMain.handle(
  "agent:reloadDocuments",
  async (_event, documentPaths: string[]) => {
    logger.info("Agent document reload requested", { documentPaths });
    await studyAgentService.reloadDocuments(documentPaths);
    return studyAgentService.getStatus();
  }
);

ipcMain.handle("agent:openFileDialog", async () => {
  const result = await dialog.showOpenDialog({
    properties: ["openFile", "multiSelections"],
    filters: [
      { name: "Documents", extensions: ["pdf", "txt", "md", "mdx"] },
      { name: "Code Files", extensions: ["ts", "tsx", "js", "jsx", "json"] },
      { name: "All Files", extensions: ["*"] },
    ],
  });

  if (result.canceled || result.filePaths.length === 0) {
    return { success: false, filePaths: [] };
  }

  return { success: true, filePaths: result.filePaths };
});

ipcMain.handle(
  "agent:addDocuments",
  async (_event, documentPaths: string[]) => {
    logger.info("Agent add documents requested", { documentPaths });

    try {
      // Mark documents as processing in database
      const trackedDocs: Array<{ docId: string; filePath: string }> = [];
      const ingestPaths: string[] = [];
      const missingFiles: string[] = [];
      const replacedDocuments: string[] = [];
      for (const filePath of documentPaths) {
        const absolutePath = path.isAbsolute(filePath)
          ? path.resolve(filePath)
          : path.resolve(process.cwd(), filePath);

        // Check if file exists first
        if (!fs.existsSync(absolutePath)) {
          logger.warn(`File not found: ${absolutePath}`);
          missingFiles.push(absolutePath);
          continue;
        }

        const existingDoc = dbManager.getDocumentByPath(absolutePath);
        if (existingDoc) {
          logger.info(
            `Re-upload requested for ${absolutePath} (ID: ${existingDoc.id})`
          );
          replacedDocuments.push(absolutePath);
          dbManager.deleteDocument(existingDoc.id);
        }

        const docId = `doc-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
        const fileName = path.basename(absolutePath);
        const fileType = path.extname(absolutePath);
        const fileSize = fs.existsSync(absolutePath)
          ? fs.statSync(absolutePath).size
          : 0;

        const doc: UploadedDocument = {
          id: docId,
          filePath: absolutePath,
          fileName,
          fileType,
          fileSize,
          chunkCount: 0,
          uploadedAt: Date.now(),
          status: "processing",
        };

        dbManager.saveDocument(doc);
        trackedDocs.push({ docId, filePath: absolutePath });
        ingestPaths.push(absolutePath);
      }

      if (ingestPaths.length === 0) {
        logger.warn("No valid documents queued for ingestion");
        const errorMessage = missingFiles.length
          ? "Some selected files could not be found."
          : "Document selection was empty.";
        return {
          success: false,
          addedCount: 0,
          errors: [errorMessage],
          documentStats: {},
        };
      }

      // Note: Document replacement is handled by the RAG service
      // When re-uploading, the new embeddings will be added to the collection

      // Process documents through agent
      const result = await studyAgentService.addDocuments(ingestPaths);

      // Update document status in database
      if (result.success) {
        for (const doc of trackedDocs) {
          const stats =
            result.documentStats[path.resolve(doc.filePath)] ?? null;
          if (stats) {
            dbManager.updateDocumentStatus(doc.docId, "ready");
            dbManager.updateDocumentChunkCount(doc.docId, stats.chunkCount);
          } else {
            dbManager.updateDocumentStatus(
              doc.docId,
              "error",
              "File did not yield usable text."
            );
          }
        }

        // Update vector store state
        const currentState = dbManager.getVectorStoreState();
        const previousDocuments = currentState?.totalDocuments ?? 0;
        const previousChunks = currentState?.totalChunks ?? 0;
        const addedChunks = Object.values(result.documentStats).reduce(
          (sum, stats) => sum + stats.chunkCount,
          0
        );

        dbManager.updateVectorStoreState(
          previousDocuments + result.addedCount,
          previousChunks + addedChunks,
          {
            lastIngestedAt: Date.now(),
            lastDocuments: Object.values(result.documentStats).map((stats) => ({
              absolutePath: stats.absolutePath,
              chunkCount: stats.chunkCount,
              origin: stats.origin,
            })),
          }
        );
      } else {
        for (const doc of trackedDocs) {
          dbManager.updateDocumentStatus(
            doc.docId,
            "error",
            result.errors.join(", ")
          );
        }
      }

      if (missingFiles.length > 0) {
        return {
          ...result,
          errors: [
            ...result.errors,
            "Some files could not be found during ingestion.",
          ],
        };
      }

      return result;
    } catch (error) {
      logger.error("Failed to add documents", error);
      return {
        success: false,
        addedCount: 0,
        errors: [error instanceof Error ? error.message : String(error)],
        documentStats: {},
      };
    }
  }
);

ipcMain.handle("config:getSummary", () => {
  return configManager.getSummary();
});

ipcMain.handle(
  "config:update",
  async (_event, values: Record<string, string | undefined>) => {
    await configManager.update(values);
    return configManager.getSummary();
  }
);

// ========================================
// Database IPC Handlers
// ========================================

/**
 * Register database IPC handlers after database is initialized
 * This ensures the database is ready before any IPC calls are made
 */
function registerDatabaseHandlers() {
  ipcMain.handle("db:saveMessage", (_event, message: ChatMessage) => {
    try {
      dbManager.saveMessage(message);
      return { success: true };
    } catch (error) {
      logger.error("Failed to save message", error);
      return {
        success: false,
        error: error instanceof Error ? error.message : String(error),
      };
    }
  });

  ipcMain.handle(
    "db:getMessages",
    (_event, threadId: string, limit?: number) => {
      try {
        return dbManager.getMessages(threadId, limit);
      } catch (error) {
        logger.error("Failed to get messages", error);
        return [];
      }
    }
  );

  ipcMain.handle("db:clearMessages", (_event, threadId: string) => {
    try {
      dbManager.clearMessages(threadId);
      return { success: true };
    } catch (error) {
      logger.error("Failed to clear messages", error);
      return {
        success: false,
        error: error instanceof Error ? error.message : String(error),
      };
    }
  });

  ipcMain.handle("db:createThread", (_event, id: string, title: string) => {
    try {
      dbManager.createThread(id, title);
      return { success: true };
    } catch (error) {
      logger.error("Failed to create thread", error);
      return {
        success: false,
        error: error instanceof Error ? error.message : String(error),
      };
    }
  });

  ipcMain.handle("db:getAllThreads", () => {
    try {
      return dbManager.getAllThreads();
    } catch (error) {
      logger.error("Failed to get threads", error);
      return [];
    }
  });

  ipcMain.handle("db:getAllDocuments", () => {
    try {
      return dbManager.getAllDocuments();
    } catch (error) {
      logger.error("Failed to get documents", error);
      return [];
    }
  });

  ipcMain.handle("db:deleteDocument", (_event, id: string) => {
    try {
      dbManager.deleteDocument(id);
      return { success: true };
    } catch (error) {
      logger.error("Failed to delete document", error);
      return {
        success: false,
        error: error instanceof Error ? error.message : String(error),
      };
    }
  });

  ipcMain.handle("db:getStats", () => {
    try {
      return dbManager.getStats();
    } catch (error) {
      logger.error("Failed to get database stats", error);
      return { threads: 0, messages: 0, documents: 0, dbSizeMB: 0 };
    }
  });

  logger.info("Database IPC handlers registered");
}

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
